#!/bin/bash -e

# Some output (stdout)
echo "Building in project dir $KONSTANT_PROJECT_ROOT ..."
echo "The build timestamp is $KONSTANT_TIMESTAMP"

# Exit with positive status code (build succeeded)
# exit 0
